version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  build-and-test:
    executor: node/default
      steps:
        - checkout
        - node/install
        - run:
            command: node_modules/.bin/mocha test/
            name: Test
workflows:
  node-tests:
    jobs:
      - build-and-test
