version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  build-and-test:
    docker:
      — image: circleci/node:7.10
    steps:
      - checkout
      - run: npm install
      - run: node_modules/.bin/mocha test/
workflows:
  node-tests:
    jobs:
      - build-and-test
